### ISSUE TITLE
Compilation fails because prettyprint.hpp doesn't exist.

### ISSUE THREAD

**Issue by darknodi** [sharmaeklavya2/ddos-on-anycast#2]
g++ -D DEBUG -g -std=c++11 -Wall -Wpedantic -c src/lib/network.cpp -o build/debug/lib/network.o
In file included from src/lib/graph_gen.hpp:4:0,
                 from src/lib/network.hpp:4,
                 from src/lib/network.cpp:1:
src/lib/base.hpp:15:48: fatal error: /mnt/code/OJ/lib/cpp/prettyprint.hpp: No such file or directory
 #include "/mnt/code/OJ/lib/cpp/prettyprint.hpp"
                                                ^
compilation terminated.
make: *** [build/debug/lib/network.o] Error 1
# 
@sharmaeklavya2

**Comment by sharmaeklavya2** [comment]
Oops. I forgot to remove that dependency. I was using a pretty-printing library created by someone else (so that `operator<<(ostream&, const vector<T>&)` works). I have replaced that by my own implementation now.

The project now compiles for me without the external dependency. I'm closing the issue. If you're still unable to compile it, reopen the issue.
